import { useEffect } from 'react'

const useDarkMode = (switchMode) => {
  const $ = (string) => document.querySelector(string)
  const $$ = (string) => document.querySelectorAll(string)

  const toDark = () => {
    const html = $('html')
    const p = $$('p')
    const h2 = $$('h2')
    const homeBody = $('.homeBody')
    const headerMainArea = $('.headerMainArea')
    const btnMenu = $('.btnMenu')
    const mainAreaContent = $('.mainAreaContent')
    const sideBar = $('.sideBar')
    const slideLink = $$('.slideLink')
    const slideLinkSelected = $$('.slideLinkSelected')
    const slideLinkIcon = $$('.slideLinkIcon')
    const hiUsername = $('.hiUsername')
    const box = $$('.box')
    const boxes = $('.boxes')
    const watchListBtn = $$('.watchListBtn')
    const addBtn = $$('.addBtn')
    const storeLogo = $('.storeLogo')
    const boxLogo = $$('.boxLogo')
    const articleBox = $$('.article-box')
    const articleImg = $$('.article-img')
    const btnBox = $$('.btn-box')
    const searchBar = $('.search-bar')
    const searchBarInput = $('.search-bar-input')
    const searchBarBtn = $('.search-bar-btn')
    const elsa = $('.elsaContainer')

    elsa?.classList.add('darkElsaContainer')
    html?.classList.add('darkHtml')
    homeBody?.classList.add('darkHomeBody')
    headerMainArea?.classList.add('darkHeaderMainArea')
    btnMenu?.classList.add('darkBtnMenu')
    mainAreaContent?.classList.add('darkMainAreaContent')
    sideBar?.classList.add('darkSideBar')
    slideLink?.forEach((elem) => elem.classList.add('darkSlideLink'))
    slideLinkSelected?.forEach((elem) => {
      elem.classList.add('darkSlideLinkSelected')
      elem.classList.remove('slideLinkSelected')
    })
    p?.forEach((elem) => elem.classList.add('darkP'))
    h2?.forEach((elem) => elem.classList.add('darkH2'))
    slideLinkIcon?.forEach((elem) => elem.classList.add('darkSlideLinkIcon'))
    box?.forEach((elem) => elem.classList.add('darkBox'))
    watchListBtn?.forEach((elem) => elem.classList.add('darkWatchListBtn'))
    hiUsername?.classList.add('darkHiUsername')
    boxes?.classList.add('darkBoxes')
    addBtn?.forEach((elm) => elm.classList.add('darkAddBtn'))
    storeLogo?.classList.add('darkStoreLogo')
    boxLogo?.forEach((elm) => elm.classList.add('darkBoxLogo'))
    articleBox?.forEach((elm) => elm.classList.add('article-box-dark'))
    articleImg?.forEach((elm) => elm.classList.add('article-img-dark'))
    btnBox?.forEach((elm) => elm.classList.add('btn-box-dark'))
    searchBar?.classList.add('search-bar-dark')
    searchBarInput?.classList.add('search-bar-input-dark')
    searchBarBtn?.classList.add('search-bar-btn-dark')
  }

  const toLight = () => {
    const html = $('html')
    const p = $$('p')
    const h2 = $$('h2')
    const homeBody = $('.homeBody')
    const headerMainArea = $('.headerMainArea')
    const btnMenu = $('.btnMenu')
    const mainAreaContent = $('.mainAreaContent')
    const sideBar = $('.sideBar')
    const slideLink = $$('.slideLink')
    const slideLinkSelected = $$('.darkSlideLinkSelected')
    const slideLinkIcon = $$('.slideLinkIcon')
    const hiUsername = $('.hiUsername')
    const box = $$('.box')
    const boxes = $('.boxes')
    const watchListBtn = $$('.watchListBtn')
    const addBtn = $$('.addBtn')
    const storeLogo = $('.storeLogo')
    const boxLogo = $$('.boxLogo')
    const main = $('main')
    const articleBox = $$('.article-box')
    const articleImg = $$('.article-img')
    const btnBox = $$('.btn-box')
    const searchBar = $('.search-bar')
    const searchBarInput = $('.search-bar-input')
    const searchBarBtn = $('.search-bar-btn')
    const elsa = $('.elsaContainer')

    elsa?.classList.remove('darkElsaContainer')
    html.classList.remove('darkHtml')
    homeBody?.classList.remove('darkHomeBody')
    headerMainArea?.classList.remove('darkHeaderMainArea')
    btnMenu?.classList.remove('darkBtnMenu')
    mainAreaContent?.classList.remove('darkMainAreaContent')
    sideBar?.classList.remove('darkSideBar')
    slideLink?.forEach((elem) => elem.classList.remove('darkSlideLink'))
    slideLinkSelected?.forEach((elem) => {
      elem.classList.remove('darkSlideLinkSelected')
      elem.classList.add('slideLinkSelected')
    })
    h2?.forEach((elem) => elem.classList.remove('darkH2'))
    p?.forEach((elem) => elem.classList.remove('darkP'))
    slideLinkIcon?.forEach((elem) => elem.classList.remove('darkSlideLinkIcon'))
    box?.forEach((elem) => elem.classList.remove('darkBox'))
    watchListBtn?.forEach((elem) => elem.classList.remove('darkWatchListBtn'))
    hiUsername?.classList.remove('darkHiUsername')
    boxes?.classList.remove('darkBoxes')
    addBtn?.forEach((elm) => elm.classList.remove('darkAddBtn'))
    storeLogo?.classList.remove('darkStoreLogo')
    boxLogo?.forEach((elm) => elm.classList.remove('darkBoxLogo'))
    main?.classList.remove('darkMainArea')
    articleBox?.forEach((elm) => elm.classList.remove('article-box-dark'))
    articleImg?.forEach((elm) => elm.classList.remove('article-img-dark'))
    btnBox?.forEach((elm) => elm.classList.remove('btn-box-dark'))
    searchBar?.classList.remove('search-bar-dark')
    searchBarInput?.classList.remove('search-bar-input-dark')
    searchBarBtn?.classList.remove('search-bar-btn-dark')
  }

  useEffect(() => {
    const isDark = localStorage.getItem('preferedTheme') === 'dark'
    switchMode && (switchMode.current.checked = isDark)
    if (isDark) toDark()
    else toLight()
    // eslint-disable-next-line
  }, [])
  return { toDark, toLight }
}

export default useDarkMode
